# Generated by Django 3.2.12 on 2022-08-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('correct', models.BooleanField(verbose_name='Правильность ответа')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='docs.category', verbose_name='Категория')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_set', to='docs.speciality', verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('introductory', 'Вводный'), ('every_shift', 'Ежесменный'), ('repeated', 'Повторный'), ('thematic', 'Тематический')], max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Закрыто')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='docs.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(verbose_name='Правильность ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('test_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='test_questions.testanswer', verbose_name='Тестовый ответ')),
                ('test_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question_set', to='test_questions.testquestion', verbose_name='Тестовый вопрос')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='test_questions.testresult', verbose_name='результат теста')),
            ],
        ),
        migrations.AddField(
            model_name='testanswer',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='test_questions.testquestion', verbose_name='тестовый вопрос'),
        ),
    ]
