# Generated by Django 3.2.12 on 2022-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='photo',
            field=models.ImageField(blank=True, upload_to='test_questions/'),
        ),
    ]
