# Generated by Django 3.2.12 on 2022-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220818_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('director', 'Директор'), ('employee', 'Сотрудник')], default='employee', max_length=128, verbose_name='Роль'),
        ),
    ]
